name: app
resolution: workspace
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ★★★ スワイプアクション用のパッケージ ★★★
  flutter_slidable: ^3.0.1

  domain:
    path: ../domain
  data:
    path: ../data
  components:
    path: ../components

  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
